version: "2.1"

services:
  # InfluxDB container
  influxdb:
    # Makes all ports accessible on the host for testing
    ports:
      - "8083:8083"

  # Grafana container
  grafana:
    ports:
      - "3000:3000"

  # Vault
  # Non production setup
  # See https://hub.docker.com/_/vault/
  vault:
    image: "vault:0.9.0"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "test"
    cap_add:
      - "IPC_LOCK"
    ports:
      - "8200"

  # Ontrack container
  ontrack:
    image: "nemerosa/ontrack:latest"
    environment:
        PROFILE: "prod"
    volumes:
      # The /var/ontrack/conf on the DO machine is filled in from gradle/compose/ci/ontrack in the doEnv task
      - "/var/ontrack/conf:/var/ontrack/conf"
      # Better startup performances in CI and DO, do not use in Prod
      - "/dev/urandom:/dev/random"
    ports:
      - "443:443"
    links:
      - "postgresql:postgresql"
      - "vault:vault"
