# InfluxDB container
influxdb:
  image: influxdb:1.1-alpine
  environment:
    PRE_CREATE_DB: "ontrack"

# Grafana container
grafana:
  build: ./common/grafana
  links:
    - "influxdb:influxdb"

# Ontrack container
ontrack:
  image: nemerosa/ontrack:latest
  environment:
    JAVA_OPTIONS: "${JAVA_OPTIONS}"
  links:
    - "influxdb:influxdb"
