# InfluxDB container
influxdb:
  restart: always

# Grafana container
grafana:
  restart: always
  ports:
    - "3000:3000"
  environment:
    GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}

# Ontrack container
ontrack:
  restart: always
  image: nemerosa/ontrack:${ONTRACK_VERSION}
  environment:
      PROFILE: prod
  volumes:
    - "/var/ontrack/conf:/var/ontrack/conf"
    - "/var/ontrack/data:/var/ontrack/data"
      # Using the random source from the host
    - "/dev/random:/dev/random"
  ports:
    - "443:443"
