language: java
sudo: required

services:
  - docker

jdk:
  - oraclejdk8
  
node_js:
  - "0.10"

before_install:
  - npm install -g bower
  - git config --global user.email "notifications@travis-ci.org"
  - git config --global user.name "Travis CI"

script:
  - ./gradlew test integrationTest -x javadoc --stacktrace
