# Production environment

spring:
  # Cache configuration
  resources:
    cache-period: 3600
  # Local database
  datasource:
    # Tomcat specific pool configuration
    # #234 Make sure the connections are renewed in the pool
    max-age: 600000

# SSL configuration
server:
  port: 443
  ssl:
    enabled: true
    # Fill the keystore information in a secret `application-prod.yml` file
    # key-alias: server
    # key-store: "config/ontrack_nemerosa_net.jks"
    # key-store-password: ***

# Ontrack configuration
ontrack:
  # Integration with InfluxDB for the metrics
  config:
    metrics-period: 10
  metrics:
    influxdb:
      # The host is defined by the Docker link ontrack -> influxdb
      # Using the default internal port because of the link
      host: influxdb
      period: 10
