version: "2"

services:
  postgres:
    image: postgres:9.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB      : ontrack
      POSTGRES_USER    : ontrack
      POSTGRES_PASSWORD: ontrack
