---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-h2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.h2.disk.size | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-h2-deployment
  labels:
    app: "h2"
    chart: {{ template "ontrack.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "h2"
      release: {{ .Release.Name }}
  strategy:
      type: Recreate
  template:
    metadata:
      labels:
        app: "h2"
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: {{ .Release.Name }}-h2-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-h2-pvc
      containers:
        - name: {{ .Chart.Name }}-h2
          image: "{{ .Values.h2.image.repository }}:{{ .Values.h2.image.version }}"
          volumeMounts:
            - mountPath: /usr/lib/h2
              name: {{ .Release.Name }}-h2-storage
          ports:
            - containerPort: 9082
              name: tcp
              protocol: TCP
            - containerPort: 8082
              name: console
              protocol: TCP
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "{{ .Release.Name }}-h2-deployment-service"
  labels:
    app: "h2"
    chart: {{ template "ontrack.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
  - protocol: "TCP"
    port: 9082
    targetPort: 9082
  selector:
    app: "h2"
    release: {{ .Release.Name }}
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-v2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ontrack.disk.size | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-v2-deployment
  labels:
    app: "ontrack"
    major: "2"
    chart: {{ template "ontrack.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "ontrack"
      major: "2"
      release: {{ .Release.Name }}
  strategy:
      type: Recreate
  template:
    metadata:
      labels:
        app: "ontrack"
        major: "2"
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: {{ .Release.Name }}-v2-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-v2-pvc
      containers:
        - name: {{ .Chart.Name }}-ontrack
          image: "{{ .Values.ontrack.image.repository }}:{{ .Values.ontrack.image.version }}"
          resources:
            limits:
              memory: "1Gi"
          env:
            - name: ONTRACK_DB_URL
              value: "jdbc:h2:tcp://{{ .Release.Name }}-h2-deployment-service:9082/ontrack;MODE=MYSQL"
            - name: JAVA_OPTIONS
              value: "-Xmx1024m -Xms1024m"
          volumeMounts:
            - mountPath: /var/ontrack/data
              name: {{ .Release.Name }}-v2-storage
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              port: http
#              path: /info
#          readinessProbe:
#            httpGet:
#              port: http
#              path: /info
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-v2-service
  labels:
    app: "ontrack"
    major: "2"
    chart: {{ template "ontrack.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: "ontrack"
    major: "2"
    release: {{ .Release.Name }}
