# InfluxDB container
influxdb:
  image: tutum/influxdb:0.9
  # Makes all ports accessible on the host for testing
  ports:
    - "8083"
    - "8086"
  environment:
    PRE_CREATE_DB: "ontrack"

# Grafana container
grafana:
  build: ./grafana
  ports:
    - "3000"
  links:
    - "influxdb:influxdb"

# Ontrack container
ontrack:
  image: nemerosa/ontrack:latest
  environment:
      PROFILE: acceptance
  volumes:
    - "./ontrack:/var/ontrack/conf"
    # Better startup performances in CI and DO, do not use in Prod
    - "/dev/urandom:/dev/random"
  ports:
    - "443"
  links:
    - "influxdb:influxdb"
