resources:
  - name: ontrack
    type: git
    source:
        uri: https://github.com/nemerosa/ontrack
        branch: experimental/concourse

jobs:
  - name: build
    plan:
      - get: ontrack
      - task: build
        file: ontrack/concourse/task-build.yml
