resources:
  - name: code
    type: git
    source:
        uri: https://github.com/nemerosa/ontrack
        branch: experimental/concourse

jobs:
  - name: build
    plan:
      - get: code
      - task: build
        file: code/concourse/task-build.yml
