# Application properties

# Flyway configuration
# See RepositoryConfig for general Flyway configuration
flyway:
  baseline-on-migrate: true

# Spring configuration
spring:
  # Default profile
  profiles:
    default: prod
  # AOP configuration
  aop:
    proxyTargetClass: true
  # Datasource configuration
  datasource:
    username: ontrack
    password: ontrack


# Management
management:
  context-path: "/manage"

# Security

# No security by default for the application end points
security:
  basic:
    enabled: false

# General information
# The version information is generated in /application.properties by the build
info:
  app:
    name: Ontrack
    description: Continuous Delivery Traceability and Monitoring
