# Application properties

# Static resources
# See DevSettings

# Database connection
spring:
  datasource:
    url: "jdbc:h2:./work/ontrack/db/data;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE;DEFRAG_ALWAYS=TRUE"
