---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ontrack-v2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ontrack-v2-deployment
  labels:
    app: "ontrack"
    major: "2"
spec:
  selector:
    matchLabels:
      app: "ontrack"
      major: "2"
  strategy:
      type: Recreate
  template:
    metadata:
      labels:
        app: "ontrack"
        major: "2"
    spec:
      volumes:
        - name: ontrack-v2-storage
          persistentVolumeClaim:
            claimName: ontrack-v2-pvc
      containers:
        - name: ontrack
          image: "nemerosa/ontrack:2.33.5"
          env:
            - name: ONTRACK_DB_URL
              value: "jdbc:h2:tcp://ontrack-h2-deployment-service:9082/ontrack;MODE=MYSQL"
          volumeMounts:
            - mountPath: /var/ontrack/data
              name: ontrack-v2-storage
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              port: http
#              path: /info
#          readinessProbe:
#            httpGet:
#              port: http
#              path: /info
---
apiVersion: v1
kind: Service
metadata:
  name: ontrack-v2-service
  labels:
    app: "ontrack"
    major: "2"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: "ontrack"
    major: "2"
