version: "2.1"

services:
   ontrack:
      image: nemerosa/ontrack:${ONTRACK_VERSION}
      environment:
         PROFILE: acceptance
   selenium:
      image: selenium/standalone-firefox
   ontrack_acceptance:
      image: nemerosa/ontrack-acceptance:${ONTRACK_VERSION}
      depends_on:
         ontrack:
            condition: service_healthy
         selenium:
            condition: service_started
      environment:
         ONTRACK_ACCEPTANCE_SELENIUM_URL: http://selenium:4444
         ONTRACK_ACCEPTANCE_TARGET_URL: http://ontrack:8080
      volumes:
        - "${ONTRACK_ACCEPTANCE_RESULTS:-./target}:/ontrack/acceptance/results"
