version: "2.1"

services:
   ontrack:
      build:
        context: "./os/debian/docker"
      tty: true
      command: "start-and-wait"
      volumes:
        - "./build/logs/ontrack:/var/log/ontrack"
   selenium:
      image: "selenium/standalone-chrome:3.11.0"
      environment:
         JAVA_OPTS: "-Xmx3072m -Xms3072m"
   ontrack_acceptance:
      image: "nemerosa/ontrack-acceptance:${ONTRACK_VERSION:-latest}"
      depends_on:
         ontrack:
            condition: service_started
         selenium:
            condition: service_started
      environment:
         ONTRACK_ACCEPTANCE_SELENIUM_GRID_URL: http://selenium:4444/wd/hub
         ONTRACK_ACCEPTANCE_SELENIUM_BROWSER_NAME: chrome
         ONTRACK_ACCEPTANCE_SELENIUM_TARGET_URL: http://ontrack:8080
         ONTRACK_ACCEPTANCE_TARGET_URL: http://ontrack:8080
         ONTRACK_ACCEPTANCE_CONTEXT: smoke
         JAVA_OPTIONS: "-Xmx2048m -Xms2048m"
      volumes:
         - "./build:/ontrack/acceptance/output:rw"
