version: "2.1"

services:
   ontrack:
      image: "nemerosa/ontrack:${ONTRACK_VERSION:-latest}"
      environment:
         PROFILE: acceptance
         ONTRACK_CONFIG_CONFIGURATION_TEST: "false"
         JAVA_OPTIONS: "-Xmx1024m"
   selenium:
      image: "selenium/standalone-firefox:3.1.0"
      environment:
         JAVA_OPTS: "-Xmx512m"
   ontrack_acceptance:
      build: docker
      depends_on:
         - ontrack
         - selenium
      environment:
         ONTRACK_ACCEPTANCE_SELENIUM_GRID_URL: http://selenium:4444/wd/hub
         ONTRACK_ACCEPTANCE_TARGET_URL: http://ontrack:8080
      volumes:
        - "${ONTRACK_ACCEPTANCE_OUTPUT:-./build/acceptance}:/ontrack/acceptance/output"
